Add odroid-N2-plus
Tow-Boot/Tow-Boot pull request #149
Opened 2022-04-26 07:39 UTC by ulrikstrid

This adds a build for the odroid N2+ computer. Also adds support for the XTX SPI XT25Q64D

2022-04-26 18:11 UTC, samueldr requested changes
:wave: Hi!

We can do more simpler. The N2 configuration is already used for N2+.

In fact, your problem is not plus vs. non-plussed N2, but that some of the batches (new ones?)  apparently are using a new yet-unsupported SPI Flash.

So, really, you can condense this into only:

> Add support for XTX SPI XT25Q64D

And apply it to the existing N2 configuration.

Adding a note here that this is desirable. When possible, board configurations should be coalesced into a single one.

2022-04-26 20:02 UTC, samueldr commented
I'll need to build it for verification, but I don't have the hardware to test.

I assume that you have now been able to successfully flash to SPI, and start your N2+ from SPI, right?

2022-04-26 20:04 UTC, ulrikstrid commented
I have not tested it with the new changes, but it builds, I can try it tomorrow.
The initial state of this PR flashes and I have managed to boot NixOS on top

2022-04-26 20:05 UTC, ulrikstrid commented
Note that the patch will not apply cleanly in upstream u-boot since they don't have the first patch.

2022-04-26 20:06 UTC, samueldr commented
> Note that the patch will not apply cleanly in upstream u-boot since they don't have the first patch.

Either you'll have submitted something to upstream, or we rebase things ourselves, so it's not a big deal. Thanks for the heads-up.

2022-04-27 15:09 UTC, ulrikstrid commented
@samueldr I can confirm that I can flash the SPI and boot into a OS with the current state of this PR

2022-06-10 21:51 UTC, samueldr commented
(Changed the base branch to force a refresh of the PR... and yesterday I though the "refresh commits" option in SourceForge was weird...)

2022-06-10 21:51 UTC, samueldr approved these changes

2022-06-10 21:51 UTC, merged

2022-06-10 21:51 UTC, samueldr commented
Thank you!